# Generated by Django 5.2.3 on 2025-07-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='posted',
            new_name='posted_at',
        ),
    ]
